add_newline = false

format = """
[\\[](bold red)\
$username\
[@](bold green)\
$hostname \
$directory\
[\\]](bold red) \
$character"""

right_format = """
$git_status\
$git_branch\
$cmd_duration"""


[username]
show_always = true                
style_user = "bold yellow"        
format = '[$user]($style)'

[hostname]
ssh_only = false                  
format = "[$hostname]($style)"    
style = 'bold blue'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = "bold yellow"

[character]
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold red)'
vimcmd_symbol = '[❯ ](bold green)'
vimcmd_visual_symbol = '[❯ ](bold yellow)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '
style = "bold black"

[cmd_duration]
format = '[$duration]($style) ' 
style = 'bold red'
